env:
  global:
    - CC_TEST_REPORTER_ID=2ed2fcb7b1be5f7e90a9cb6d760634c06266944096fb815a1e8126f95092b636
language: java
sudo: false
cache:
  directories: "$HOME/.m2"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - mvn test
after_script:
  - mv "./target/site/jacoco/jacoco.xml" "./src/main/java/jacoco.xml"
  - cd ./src/main/java/
  - ../../../cc-test-reporter after-build -t jacoco --exit-code $TRAVIS_TEST_RESULT
